GET http://localhost:3000/users
###
POST http://localhost:3000/users
  content-type: application/json

    {
       "id": 6,
       "name": "Vin",
       "surname": "Diesel",
       "age": 55
    }
###
PUT http://localhost:3000/users/5
    content-type: application/json

    {
       "name": "AZIZ"
    }
###
DELETE http://localhost:3000/users/1