const TOKEN_SECRET = 'RANDOM_TOKEN_SECRET';
const DEFAULT_PAGE_LIMIT = 20;
const DEFAULT_PROJECT_PAGE_LIMIT = 100;

module.exports = {
  TOKEN_SECRET,
  DEFAULT_PAGE_LIMIT,
  DEFAULT_PROJECT_PAGE_LIMIT,
};
