B:=$(~/Desktop/swe-itc-13-homeworks/Margarita_Hambaryan/Make_Cmake/27_12_2021/a/b)
C:=$(~/Desktop/swe-itc-13-homeworks/Margarita_Hambaryan/Make_Cmake/27_12_2021/a/c)

all: subdir

subdir: $(B) $(C)
	$(MAKE) -C $@

clean:
	$(MAKE) -C clean
