# Generated by Django 4.0.4 on 2022-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_user_delete_user_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
